# Permalinks
permalink:           pretty

# Setup
title:               Xixuan Zhang
tagline:             Data | AI | Social Science
url:                 "https://xixuanzhang2022.github.io"
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            compressed

# About/contact
author:
  name:              Xixuan Zhang
  url:               xixuanzhang2022.github.io
  email:             xixuan.zh@gmail.com

# Custom vars
version:             2.0.1
github:
  repo:              https://github.com/xixuanzhang2022/xixuanzhang2022.github.io
google_analytics:
twitter:
github:              xixuanzhang2022
dribbble:

# Gems
plugins:
  # - jekyll-paginate
  # - jekyll-gist

collections:
  publications:
    output: true   # means each item will have its own page
    permalink: /publications/:path/
